---
- name: Restart gitlab-runner
  ansible.builtin.service:
    name: gitlab-runner
    state: restarted
  become: true

- name: Restart docker
  ansible.builtin.service:
    name: docker
    state: restarted
  become: true
  listen: Restart docker
